filter:
  excluded_paths: [node_modules/*, dist/*, asset/*, lib/*, simulate/*, 'test/*', 'out/*]

build:
  dependencies:
    before:
      - npm install   # or add it as part of your package.json

    tests:
      override:
        -
          command: 'npm run coverage-test'
          coverage:
            file: 'coverage/clover.xml'
            format: 'clover'
